version: '3.7'
# used for local testing
# note only have either mfcs_export or mnt not both for conversions or hyrax.
services:
  hyrax:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: hyrax
    env_file:
      - './env/.env.dev.hyrax'       
    restart: on-failure           
    depends_on:
      - fcrepo
      - postgres
      - solr
      - memcached      
    ports:
      - 3000:3000
    volumes:
      - ./hyrax:/home/hyrax
      - hyrax_tmp:/home/hyrax/tmp
    networks:
      - hyrax   

  sidekiq:
    container_name: hyrax_sidekiq
    build: 
      context: ./
      dockerfile: Dockerfile
    command: sh -l -c 'bundle && bundle exec sidekiq'
    env_file:
      - './env/.env.dev.hyrax'     
    restart: always      
    volumes:
      - ./hyrax:/home/hyrax          
    depends_on:
      - fcrepo
      - postgres
      - solr
      - memcached
    networks:
      - hyrax     

  memcached:
    image: bitnami/memcached
    container_name: hyrax_memcached
    ports:
      - '11211:11211'
    networks:
      - hyrax

  redis:
    image: redis:alpine
    container_name: hyrax_redis
    command: redis-server
    volumes:
      - redis:/var/lib/redis/data
    restart: unless-stopped  
    healthcheck:
      test: redis-cli -h redis ping
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - hyrax                              

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    container_name: hyrax_fcrepo
    restart: on-failure    
    volumes:
      - fcrepo:/data:cached
    ports:
      - "8080:8080"
    networks:
      - hyrax 
      
  solr:
    image: solr:8.11.1
    container_name: wvu_solr
    restart: on-failure
    ports:
      - 8983:8983
    command:
      - sh
      - "-c"
      - "solr-precreate hyrax_dev /opt/solr/server/configsets/hyraxconf"
    volumes:
      - solr:/var/solr/data:cached
      - ./hyrax/solr/conf:/opt/solr/server/configsets/hyraxconf
    networks:
      - hyrax 

  postgres:
    container_name: hyrax_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - './env/.env.dev.db'       
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
        test: pg_isready -U postgres -h postgres
        interval: 30s
        timeout: 3s
        retries: 3
    networks:
      - hyrax 

volumes:
  hyrax_tmp:
  postgres:
  fcrepo:
  redis:
  solr:

networks:
  hyrax:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-hyrax 

