# test setup for testing production setup
# locally.

version: '3.7'

services:
  hydra:
    build: 
      context: ./
      dockerfile: Dockerfile.prod
    container_name: %%project_name%%_hydra
    env_file:
      - './env/.env.prod.test.hydra'       
    restart: on-failure           
    depends_on:
      - fcrepo
      - db
      - solr
    ports:
      - 3000:3000
    volumes:
      - ./hydra:/home/hydra
      - ./solr/conf:/home/hydra/solr/conf  
      #- ./mfcs_export:/mfcs_export  
      - ./mnt:/mnt                      

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    container_name: %%project_name%%_fcrepo
    restart: on-failure    
    volumes:
      - ./fedora/data:/data:cached
    ports:
      - "8080:8080"  
      
  solr:
    image: solr:8.11.1
    container_name: %%project_name%%_solr
    restart: on-failure
    ports:
      - 8983:8983
    command:
      - sh
      - "-c"
      - "solr-precreate hydra_prod /opt/solr/server/configsets/hydraconf"
    volumes:
      - ./solr/data:/var/solr/data:cached
      - ./solr/conf:/opt/solr/server/configsets/hydraconf    

  db:
    image: mysql:5.7.27
    container_name: %%project_name%%_mysql
    restart: on-failure
    ports:
      - "3306"
    env_file:
      - './env/.env.prod.test.db'      
    volumes:
      - ./mysql:/var/lib/mysql

  conversion:
    build: 
      context: ./conversion/
      dockerfile: Dockerfile
    container_name: %%project_name%%_conversion
    restart: on-failure
    env_file:
      - './env/.env.prod.conversion' 
    volumes:
      - ./conversion/scripts:/convert/
      - ./conversion/control:/control/
      #- ./mfcs_export:/mfcs_export
      - ./mnt:/mnt
