FROM ruby:2.7

ENV BUNDLER_VERSION=2.3.19
ENV RAILS_VERSION=5.2.6

RUN mkdir -p /home/wvu_hyrax/
WORKDIR /home/wvu_hyrax
ADD . /home/wvu_hyrax

RUN apt-get update && apt-get -y install cron postgresql-client yarn build-essential vim graphicsmagick ghostscript ffmpeg openjdk-11-jdk

# Use JEMALLOC instead
# JEMalloc is a faster garbage collection for Ruby.
# -------------------------------------------------------------------------------------------------
RUN apt-get install -y libjemalloc2 libjemalloc-dev
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so

RUN \
  gem update --system --quiet && \
  gem install bundler -v ${BUNDLER_VERSION} && \
  gem install rails -v ${RAILS_VERSION} && \
  bundle install --jobs=4 --retry=3 

RUN mkdir -p /home/fits && \
    cd /home/fits && \
    wget https://github.com/harvard-lts/fits/releases/download/1.5.1/fits-1.5.1.zip -O fits.zip && \
    unzip fits.zip && \
    rm fits.zip && \
    chmod a+x /home/fits/fits.sh
ENV PATH="${PATH}:/home/fits"

# Node.js
RUN curl -sL https://deb.nodesource.com/setup_17.x | bash - \
    && apt-get install -y nodejs