version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password   

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5
    container_name: fcrepo
    restart: on-failure    
    volumes:
      - fcrepo:/data:cached
    ports:
      - "8080:8080"  
      
  solr:
    container_name: solr  
    image: solr:8.11.1
    restart: on-failure
    ports:
      - "8983"
    command:
      - sh
      - "-c"
      - "precreate-core hyrax_test /opt/solr/server/configsets/hyraxconf; solr-precreate hyrax_dev /opt/solr/server/configsets/hyraxconf"
    volumes:
      - solr:/var/solr/data:cached
      - ./hyrax/solr/conf:/opt/solr/server/configsets/hyraxconf

  redis:
    image: 'redis:5-alpine'
    container_name: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'   

  sidekiq:
    container_name: sidekiq
    depends_on:
      - 'db'
      - 'fcrepo'
      - 'solr'
      - 'redis' 
    build: .
    command: bundle exec sidekiq
    volumes_from:
      - hyrax                              
    environment:
      RAILS_ENV: development
      REDIS_URL_SIDEKIQ: redis://redis:6379/12
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_PASSWORD: password
      DATABASE_HOST: db    
      #FEDORA_DEV_URL: http://fcrepo:8080/rest/
      FCREPO_HOST: fcrepo
      FCREPO_PORT: 8080
      FEDORA_PASSWORD: fedoraAdmin
      SOLR_DEV_URL: http://solr:8983/solr/hyrax_dev/
      SOLR_TEST_URL: http://solr:8983/solr/hyrax_test/    

  hyrax:
    container_name: hyrax
    depends_on:
      - 'db'
      - 'fcrepo'
      - 'solr'
      - 'redis' 
    build: 
      context: ./
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' -e development"
    ports:
      - '3000:3000'
    volumes:
      - ./hyrax:/home/hyrax
      - /home/hyrax/tmp # don't mount tmp directory
      - ./scripts:/home/hyrax/scripts      
      - ./mnt/nfs-exports/hyrax-exports:/home/hyrax/imports                        
    environment:
      RAILS_ENV: development
      REDIS_URL_SIDEKIQ: redis://redis:6379/12
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_PASSWORD: password
      DATABASE_HOST: db    
      #FEDORA_DEV_URL: http://fcrepo:8080/rest/
      FCREPO_HOST: fcrepo
      FCREPO_PORT: 8080
      FEDORA_PASSWORD: fedoraAdmin
      SOLR_DEV_URL: http://solr:8983/solr/hyrax_dev/
      SOLR_TEST_URL: http://solr:8983/solr/hyrax_test/  

volumes:
  postgres:
  fcrepo:
  solr:
  redis: