version: '3.4'
# used for local testing
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    env_file:
      - './env/.env.dev.hyrax' 
    volumes:
      - ./hyrax:/home/hyrax
      - ./scripts:/home/hyrax/scripts
      - bundle:/usr/local/bundle

      # added because we were using exports with bulkrax for testing atm
      - ./mnt/nfs-exports/hyrax-exports:/home/hyrax/imports
      - '/home/hyrax/tmp' # don't mount tmp directory     
    networks:
      - hyrax         

  web:
    extends: app
    container_name: hyrax
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - solr
      - fcrepo
      - db
      - workers
  
  workers:
    extends: app
    container_name: sidekiq
    command: bundle exec sidekiq --logfile log/sidekiq.log
    depends_on:
      - redis
      - solr
      - fcrepo
      - memcached 
      - db
    stdin_open: true
    tty: true

  memcached:
    image: bitnami/memcached
    container_name: memcached
    ports:
      - "11211"
    networks:
      - hyrax

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379"
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - hyrax
    restart: unless-stopped  
    healthcheck:
      test: redis-cli -h redis ping
      interval: 30s
      timeout: 3s
      retries: 3                                

  fcrepo:
    container_name: fcrepo
    image: ghcr.io/samvera/fcrepo4:4.7.5
    volumes:
      - fcrepo:/data:cached
    ports:
      - "8080:8080"
    networks:
      - hyrax
      
  solr:
    container_name: solr  
    image: solr:8.11.1
    restart: on-failure
    ports:
      - "8983"
    command:
      - sh
      - "-c"
      - "precreate-core hyrax_test /opt/solr/server/configsets/hyraxconf; solr-precreate hyrax_dev /opt/solr/server/configsets/hyraxconf"
    volumes:
      - solr:/var/solr/data:cached
      - ./hyrax/solr/conf:/opt/solr/server/configsets/hyraxconf
    networks:
      - hyrax 

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "5432"
    env_file:
      - './env/.env.dev.db'       
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
        test: pg_isready -U postgres -h postgres
        interval: 30s
        timeout: 3s
        retries: 3
    networks:
      - hyrax 

volumes:
  bundle:
  postgres:
  fcrepo:
  redis:
  solr:

networks:
  hyrax:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-hyrax 

