source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'

# Rails Dependencies
# =====================================================
gem 'rails', '~> 5.2.6'
gem 'puma', '~> 3.11'
gem 'pg', '>= 0.18', '< 2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'turbolinks', '~> 5'

# Hyrax Dependencies
# =====================================================
gem 'hyrax', '3.4.1'
gem 'hydra-role-management'
gem 'riiif', '~> 2.1'

gem 'rsolr', '>= 1.0', '< 3'
gem 'bootstrap-sass', '~> 3.0'
gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Application Specific
# =================================================================

# background jobs
# =====================================================
gem 'sidekiq'
gem "sidekiq-cron", "~> 1.1"
gem 'sidekiq-failures'

# authentication
# =====================================================
gem 'devise', '~> 4.6', '>= 4.6.2'
gem 'devise-guests', '~> 0.6'
gem 'omniauth', '~> 1.9'
gem 'omniauth-cas', '~> 1.1', '>= 1.1.1'

# Development / Test Items (Primarily debugging)
# =====================================================================================
group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

group :development, :test do
  gem 'solr_wrapper', '>= 0.3'  
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]  
  gem 'fcrepo_wrapper'
  gem 'rspec-rails'
end