source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.8'

# Rails
# ==============================================================================
gem 'pg', '~> 1.1'
gem 'puma'
gem 'rails', '~> 6.1.6', '>= 6.1.6.1'
gem 'webpacker', '~> 5.2', '>= 5.2.1'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Application Specific
# ==============================================================================

# background jobs
# =====================================================
gem 'sidekiq'
gem "sidekiq-cron", "~> 1.1"
gem 'sidekiq-failures'

# authentication
# =====================================================
gem 'devise'
gem 'devise-guests', '~> 0.8'
gem 'devise_cas_authenticatable'

# user management
# =====================================================
gem 'samvera-persona', git: 'https://github.com/wvulibraries/samvera-persona', branch: 'hyrax-4'

gem 'sass-rails', '>= 6'
gem 'jsbundling-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# https://github.com/redis/hiredis-rb
gem 'hiredis' # optional

# for sessions
gem 'redis-actionpack'

# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Health Check
# =====================================================
gem 'okcomputer'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Hydra Dependencies
# =====================================================
gem 'hydra-role-management'
gem 'hydra-editor'

# Hyrax Dependencies
# =====================================================
gem 'hyrax', '~> 4'
gem 'rsolr', '>= 1.0', '< 3'

gem 'bootstrap', '~> 4.0'
gem 'twitter-typeahead-rails', '0.11.1.pre.corejavascript'
gem 'jquery-rails'
gem 'openseadragon', '>= 0.2.0'
gem 'riiif', '~> 2.1'

# pdfjs for displaying PDF files in views
gem 'pdfjs_viewer-rails'

# Bulkrax Import
# =====================================================
gem 'bulkrax'

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver', '>= 4.0.0.rc1'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]  
  gem 'solr_wrapper', '>= 0.3'
  gem 'factory_bot_rails'
  gem 'faker'  
  gem 'fcrepo_wrapper'
  gem 'rspec-rails'
end
