development:
  adapter: solr
  url: <%= ENV['SOLR_DEV_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_DEVELOPMENT_PORT', 8983)}/solr/hyrax-development" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8985)}/solr/hyrax-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_PROD_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>

