development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_DEV_URL']%>
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_DEV_URL']%>
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FEDORA_PROD_URL']%>
  base_path: /prod

