:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

development:
  :concurrency: 5

production:
  :concurrency: 10

:max_retries: 1

:queues:
  - default
  - ingest
  - import
  - export
  - fixity
  - mailers
  - doi