:queues:
  - [ingest, 4]
  - [batch, 2]
  - [attach, 2] # custom queue for attaching files
  - [import, 1] # This is for bulkrax
  - [export, 1] # This is for bulkrax  
  - [derivatives, 1] # custom queue for creating derivatives
  - [default, 1]
  - [fixity, 1]
  - [mailers, 1]
  - [doi, 1]  

test: # n/a
  :concurrency: 1

development:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 2 %>
  :logfile: ./log/sidekiq_development.log

production:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 5 %>