  :queues:
    - [default, 1]
    - [import, 1] # This is for bulkrax
    - [export, 1] # This is for bulkrax
    - [fixity, 1]
    - [mailers, 1]
    - [doi, 1]
    - [batch, 1]
    - [ingest, 1]
    - [derivatives, 1]
   
  test: # n/a
    :concurrency: 1

  development:
    :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 1 %>

  production:
    :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 5 %>