# frozen_string_literal: true
# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base
  include ::Hyrax::FileSetBehavior

  after_create :create_checksum_record

  private

  def create_checksum_record
    Checksum.where(:fileset_id => self.id).first_or_create(:ingest_date => Date.today, :ingest_week_no => Date.today.strftime("%U").to_i, :file_name => self.label )
  end

end
